# Generated by Django 3.2.6 on 2022-05-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('git_url', models.URLField(blank=True, max_length=500)),
                ('top5_repos', models.TextField(blank=True, max_length=2000)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('total_repos', models.IntegerField(default=0)),
                ('all_repos', models.TextField(blank=True, max_length=5000)),
                ('orgs', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
