# Generated by Django 3.2.6 on 2022-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500)),
                ('owner', models.CharField(blank=True, max_length=500)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('homepage', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(blank=True, max_length=500)),
                ('fork_counts', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('stargazers_count', models.IntegerField(default=0)),
                ('watchers', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('topics', models.TextField(blank=True, max_length=1000)),
                ('languages', models.TextField(blank=True, max_length=1000)),
                ('content', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
